package br.com.svr.service.constante;

public enum ParametroConfiguracaoSistema {
	CNAE, CODIGO_MUNICIPIO_GERADOR_ICMS, DIAS_INATIVIDADE_CLIENTE, DIRETORIO_XML_NFE, EXPIRACAO_REGISTRO_ESTOQUE_MESES, NOME_SERVIDOR_SMTP, PERCENTUAL_COFINS, PERCENTUAL_PIS, PORTA_SERVIDOR_SMTP, REGIME_TRIBUTACAO, SSL_HABILITADO_PARA_SMTP
}
