package br.com.svr.service.constante;

public enum TipoPagamento {
	FOLHA_PAGAMENTO,
	INSUMO, 
	DESPESAS_FIXAS, 
	ACAO_JUDICIAL,
	EQUIPAMENTO, 
	EVENTUALIDADE,
	IMPOSTO,
	PRESTACAO_SERVICO,
	FRETE,
	BENEFICIOS_FOLHA,
	ICMS,
	BANCOS_EMPRESTIMOS_JUROS;
}
