drop table IF EXISTS vendas.tb_cfop cascade;

create table vendas.tb_cfop (
	codigo integer not null,
	descricao varchar(400) not null 
);
ALTER TABLE vendas.tb_cfop ADD PRIMARY KEY (codigo);

insert into vendas.tb_cfop (codigo, descricao) values (1101, 'Compra p/ industrializacao ou producao rural');
insert into vendas.tb_cfop (codigo, descricao) values (1102, 'Compra p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (1111, 'Compra p/ industrializacao de mercadoria recebida anteriormente em consignacao industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1113, 'Compra p/ comercializacao, de mercadoria recebida anteriormente em consignacao mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (1116, 'Compra p/ industrializacao ou producao rural originada de encomenda p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (1117, 'Compra p/ comercializacao originada de encomenda p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (1118, 'Compra de mercadoria p/ comercializacao pelo adquirente originario, entregue pelo vendedor remetente ao destinatario, em venda a ordem.');
insert into vendas.tb_cfop (codigo, descricao) values (1120, 'Compra p/ industrializacao, em venda a ordem, ja recebida do vendedor remetente');
insert into vendas.tb_cfop (codigo, descricao) values (1121, 'Compra p/ comercializacao, em venda a ordem, ja recebida do vendedor remetente');
insert into vendas.tb_cfop (codigo, descricao) values (1122, 'Compra p/ industrializacao em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (1124, 'Industrializacao efetuada por outra empresa');
insert into vendas.tb_cfop (codigo, descricao) values (1125, 'Industrializacao efetuada por outra empresa quando a mercadoria remetida p/ utilizacao no processo de industrializacao nao transitou pelo estabelecimento adquirente da mercadoria');
insert into vendas.tb_cfop (codigo, descricao) values (1126, 'Compra p/ utilizacao na prestacao de servico sujeita ao ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (1128, 'Compra p/ utilizacao na prestacao de servico sujeita ao ISSQN');
insert into vendas.tb_cfop (codigo, descricao) values (1151, 'Transferencia p/ industrializacao ou producao rural');
insert into vendas.tb_cfop (codigo, descricao) values (1152, 'Transferencia p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (1153, 'Transferencia de energia eletrica p/ distribuicao');
insert into vendas.tb_cfop (codigo, descricao) values (1154, 'Transferencia p/ utilizacao na prestacao de servico');
insert into vendas.tb_cfop (codigo, descricao) values (1201, 'Devolucao de venda de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (1202, 'Devolucao de venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (1203, 'Devolucao de venda de producao do estabelecimento, destinada a ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (1204, 'Devolucao de venda de mercadoria adquirida ou recebida de terceiros, destinada a ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (1205, 'Anulacao de valor relativo a prestacao de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (1206, 'Anulacao de valor relativo a prestacao de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (1207, 'Anulacao de valor relativo a venda de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (1208, 'Devolucao de producao do estabelecimento, remetida em transferencia');
insert into vendas.tb_cfop (codigo, descricao) values (1209, 'Devolucao de mercadoria adquirida ou recebida de terceiros, remetida em transferencia');
insert into vendas.tb_cfop (codigo, descricao) values (1212, 'Devolucao de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (1251, 'Compra de energia eletrica p/ distribuicao ou comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (1252, 'Compra de energia eletrica por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1253, 'Compra de energia eletrica por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (1254, 'Compra de energia eletrica por estabelecimento prestador de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (1255, 'Compra de energia eletrica por estabelecimento prestador de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (1256, 'Compra de energia eletrica por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (1257, 'Compra de energia eletrica p/ consumo por demanda contratada');
insert into vendas.tb_cfop (codigo, descricao) values (1301, 'Aquisicao de servico de comunicacao p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (1302, 'Aquisicao de servico de comunicacao por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1303, 'Aquisicao de servico de comunicacao por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (1304, 'Aquisicao de servico de comunicacao por estabelecimento de prestador de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (1305, 'Aquisicao de servico de comunicacao por estabelecimento de geradora ou de distribuidora de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (1306, 'Aquisicao de servico de comunicacao por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (1351, 'Aquisicao de servico de transporte p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (1352, 'Aquisicao de servico de transporte por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1353, 'Aquisicao de servico de transporte por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (1354, 'Aquisicao de servico de transporte por estabelecimento de prestador de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (1355, 'Aquisicao de servico de transporte por estabelecimento de geradora ou de distribuidora de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (1356, 'Aquisicao de servico de transporte por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (1360, 'Aquisicao de servico de transporte por contribuinte-substituto em relacao ao servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (1401, 'Compra p/ industrializacao ou producao rural de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1403, 'Compra p/ comercializacao em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1406, 'Compra de bem p/ o ativo imobilizado cuja mercadoria esta sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1407, 'Compra de mercadoria p/ uso ou consumo cuja mercadoria esta sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1408, 'Transferencia p/ industrializacao ou producao rural de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1409, 'Transferencia p/ comercializacao em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1410, 'Devolucao de venda de mercadoria, de producao do estabelecimento, sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1411, 'Devolucao de venda de mercadoria adquirida ou recebida de terceiros em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1414, 'Retorno de mercadoria de producao do estabelecimento, remetida p/ venda fora do estabelecimento, sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1415, 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida p/ venda fora do estabelecimento em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1451, 'Retorno de animal do estabelecimento produtor');
insert into vendas.tb_cfop (codigo, descricao) values (1452, 'Retorno de insumo nao utilizado na producao');
insert into vendas.tb_cfop (codigo, descricao) values (1501, 'Entrada de mercadoria recebida com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (1503, 'Entrada decorrente de devolucao de produto, de fabricacao do estabelecimento, remetido com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (1504, 'Entrada decorrente de devolucao de mercadoria remetida com fim especifico de exportacao, adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (1505, 'Entrada decorrente de devolucao simbolica de mercadoria remetida p/ formacao de lote de exportacao, de produto industrializado ou produzido pelo proprio estabelecimento.');
insert into vendas.tb_cfop (codigo, descricao) values (1506, 'Entrada decorrente de devolucao simbolica de mercadoria, adquirida ou recebida de terceiros, remetida p/ formacao de lote de exportacao.');
insert into vendas.tb_cfop (codigo, descricao) values (1551, 'Compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (1552, 'Transferencia de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (1553, 'Devolucao de venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (1554, 'Retorno de bem do ativo imobilizado remetido p/ uso fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (1555, 'Entrada de bem do ativo imobilizado de terceiro, remetido p/ uso no estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (1556, 'Compra de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (1557, 'Transferencia de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (1601, 'Recebimento, por transferencia, de credito de ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (1602, 'Recebimento, por transferencia, de saldo credor do ICMS, de outro estabelecimento da mesma empresa, p/ compensacao de saldo devedor do imposto. ');
insert into vendas.tb_cfop (codigo, descricao) values (1603, 'Ressarcimento de ICMS retido por substituicao tributaria');
insert into vendas.tb_cfop (codigo, descricao) values (1604, 'Lancamento do credito relativo a compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (1605, 'Recebimento, por transferencia, de saldo devedor do ICMS de outro estabelecimento da mesma empresa');
insert into vendas.tb_cfop (codigo, descricao) values (1651, 'Compra de combustivel ou lubrificante p/ industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (1652, 'Compra de combustivel ou lubrificante p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (1653, 'Compra de combustivel ou lubrificante por consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (1658, 'Transferencia de combustivel ou lubrificante p/ industrializacao');
insert into vendas.tb_cfop (codigo, descricao) values (1659, 'Transferencia de combustivel ou lubrificante p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (1660, 'Devolucao de venda de combustivel ou lubrificante destinados a industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (1661, 'Devolucao de venda de combustivel ou lubrificante destinados a comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (1662, 'Devolucao de venda de combustivel ou lubrificante destinados a consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (1663, 'Entrada de combustivel ou lubrificante p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (1664, 'Retorno de combustivel ou lubrificante remetidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (1901, 'Entrada p/ industrializacao por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (1902, 'Retorno de mercadoria remetida p/ industrializacao por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (1903, 'Entrada de mercadoria remetida p/ industrializacao e nao aplicada no referido processo');
insert into vendas.tb_cfop (codigo, descricao) values (1904, 'Retorno de remessa p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (1905, 'Entrada de mercadoria recebida p/ deposito em deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (1906, 'Retorno de mercadoria remetida p/ deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (1907, 'Retorno simbolico de mercadoria remetida p/ deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (1908, 'Entrada de bem por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (1909, 'Retorno de bem remetido por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (1910, 'Entrada de bonificacao, doacao ou brinde');
insert into vendas.tb_cfop (codigo, descricao) values (1911, 'Entrada de amostra gratis');
insert into vendas.tb_cfop (codigo, descricao) values (1912, 'Entrada de mercadoria ou bem recebido p/ demonstracao');
insert into vendas.tb_cfop (codigo, descricao) values (1913, 'Retorno de mercadoria ou bem remetido p/ demonstracao');
insert into vendas.tb_cfop (codigo, descricao) values (1914, 'Retorno de mercadoria ou bem remetido p/ exposicao ou feira');
insert into vendas.tb_cfop (codigo, descricao) values (1915, 'Entrada de mercadoria ou bem recebido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (1916, 'Retorno de mercadoria ou bem remetido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (1917, 'Entrada de mercadoria recebida em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1918, 'Devolucao de mercadoria remetida em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1919, 'Devolucao simbolica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1920, 'Entrada de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (1921, 'Retorno de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (1922, 'Lancamento efetuado a titulo de simples faturamento decorrente de compra p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (1923, 'Entrada de mercadoria recebida do vendedor remetente, em venda a ordem');
insert into vendas.tb_cfop (codigo, descricao) values (1924, 'Entrada p/ industrializacao por conta e ordem do adquirente da mercadoria, quando esta nao transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (1925, 'Retorno de mercadoria remetida p/ industrializacao por conta e ordem do adquirente da mercadoria, quando esta nao transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (1926, 'Lancamento efetuado a titulo de reclassificacao de mercadoria decorrente de formacao de kit ou de sua desagregacao');
insert into vendas.tb_cfop (codigo, descricao) values (1931, 'Lancamento efetuado pelo tomador do servico de transporte, quando a responsabilidade de retencao do imposto for atribuida ao remetente ou alienante da mercadoria, pelo servico de transporte realizado por transportador autonomo ou por transportador nao-inscrito na UF onde se tenha iniciado o servico.');
insert into vendas.tb_cfop (codigo, descricao) values (1932, 'Aquisicao de servico de transporte iniciado em UF diversa daquela onde esteja inscrito o prestador');
insert into vendas.tb_cfop (codigo, descricao) values (1933, 'Aquisicao de servico tributado pelo Imposto sobre Servicos de Qualquer Natureza');
insert into vendas.tb_cfop (codigo, descricao) values (1934, 'Entrada simbolica de mercadoria recebida p/ deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (1949, 'Outra entrada de mercadoria ou prestacao de servico nao especificada');
insert into vendas.tb_cfop (codigo, descricao) values (2101, 'Compra p/ industrializacao ou producao rural');
insert into vendas.tb_cfop (codigo, descricao) values (2102, 'Compra p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (2111, 'Compra p/ industrializacao de mercadoria recebida anteriormente em consignacao industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2113, 'Compra p/ comercializacao, de mercadoria recebida anteriormente em consignacao mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (2116, 'Compra p/ industrializacao ou producao rural originada de encomenda p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (2117, 'Compra p/ comercializacao originada de encomenda p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (2118, 'Compra de mercadoria p/ comercializacao pelo adquirente originario, entregue pelo vendedor remetente ao destinatario, em venda a ordem');
insert into vendas.tb_cfop (codigo, descricao) values (2120, 'Compra p/ industrializacao, em venda a ordem, ja recebida do vendedor remetente');
insert into vendas.tb_cfop (codigo, descricao) values (2121, 'Compra p/ comercializacao, em venda a ordem, ja recebida do vendedor remetente');
insert into vendas.tb_cfop (codigo, descricao) values (2122, 'Compra p/ industrializacao em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (2124, 'Industrializacao efetuada por outra empresa');
insert into vendas.tb_cfop (codigo, descricao) values (2125, 'Industrializacao efetuada por outra empresa quando a mercadoria remetida p/ utilizacao no processo de industrializacao nao transitou pelo estabelecimento adquirente da mercadoria');
insert into vendas.tb_cfop (codigo, descricao) values (2126, 'Compra p/ utilizacao na prestacao de servico sujeita ao ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (2128, 'Compra p/ utilizacao na prestacao de servico sujeita ao ISSQN');
insert into vendas.tb_cfop (codigo, descricao) values (2151, 'Transferencia p/ industrializacao ou producao rural');
insert into vendas.tb_cfop (codigo, descricao) values (2152, 'Transferencia p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (2153, 'Transferencia de energia eletrica p/ distribuicao');
insert into vendas.tb_cfop (codigo, descricao) values (2154, 'Transferencia p/ utilizacao na prestacao de servico');
insert into vendas.tb_cfop (codigo, descricao) values (2201, 'Devolucao de venda de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (2202, 'Devolucao de venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (2203, 'Devolucao de venda de producao do estabelecimento destinada a ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (2204, 'Devolucao de venda de mercadoria adquirida ou recebida de terceiros, destinada a ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (2205, 'Anulacao de valor relativo a prestacao de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (2206, 'Anulacao de valor relativo a prestacao de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (2207, 'Anulacao de valor relativo a venda de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (2208, 'Devolucao de producao do estabelecimento, remetida em transferencia.');
insert into vendas.tb_cfop (codigo, descricao) values (2209, 'Devolucao de mercadoria adquirida ou recebida de terceiros e remetida em transferencia');
insert into vendas.tb_cfop (codigo, descricao) values (2212, 'Devolucao de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (2251, 'Compra de energia eletrica p/ distribuicao ou comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (2252, 'Compra de energia eletrica por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2253, 'Compra de energia eletrica por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (2254, 'Compra de energia eletrica por estabelecimento prestador de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (2255, 'Compra de energia eletrica por estabelecimento prestador de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (2256, 'Compra de energia eletrica por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (2257, 'Compra de energia eletrica p/ consumo por demanda contratada');
insert into vendas.tb_cfop (codigo, descricao) values (2301, 'Aquisicao de servico de comunicacao p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (2302, 'Aquisicao de servico de comunicacao por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2303, 'Aquisicao de servico de comunicacao por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (2304, 'Aquisicao de servico de comunicacao por estabelecimento de prestador de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (2305, 'Aquisicao de servico de comunicacao por estabelecimento de geradora ou de distribuidora de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (2306, 'Aquisicao de servico de comunicacao por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (2351, 'Aquisicao de servico de transporte p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (2352, 'Aquisicao de servico de transporte por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2353, 'Aquisicao de servico de transporte por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (2354, 'Aquisicao de servico de transporte por estabelecimento de prestador de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (2355, 'Aquisicao de servico de transporte por estabelecimento de geradora ou de distribuidora de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (2356, 'Aquisicao de servico de transporte por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (2401, 'Compra p/ industrializacao ou producao rural de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2403, 'Compra p/ comercializacao em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2406, 'Compra de bem p/ o ativo imobilizado cuja mercadoria esta sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2407, 'Compra de mercadoria p/ uso ou consumo cuja mercadoria esta sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2408, 'Transferencia p/ industrializacao ou producao rural de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2409, 'Transferencia p/ comercializacao em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2410, 'Devolucao de venda de producao do estabelecimento, quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2411, 'Devolucao de venda de mercadoria adquirida ou recebida de terceiros em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2414, 'Retorno de producao do estabelecimento, remetida p/ venda fora do estabelecimento, quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2415, 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida p/ venda fora do estabelecimento em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2501, 'Entrada de mercadoria recebida com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (2503, 'Entrada decorrente de devolucao de produto industrializado pelo estabelecimento, remetido com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (2504, 'Entrada decorrente de devolucao de mercadoria remetida com fim especifico de exportacao, adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (2505, 'Entrada decorrente de devolucao simbolica de mercadoria remetida p/ formacao de lote de exportacao, de produto industrializado ou produzido pelo proprio estabelecimento.');
insert into vendas.tb_cfop (codigo, descricao) values (2506, 'Entrada decorrente de devolucao simbolica de mercadoria, adquirida ou recebida de terceiros, remetida p/ formacao de lote de exportacao.');
insert into vendas.tb_cfop (codigo, descricao) values (2551, 'Compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (2552, 'Transferencia de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (2553, 'Devolucao de venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (2554, 'Retorno de bem do ativo imobilizado remetido p/ uso fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (2555, 'Entrada de bem do ativo imobilizado de terceiro, remetido p/ uso no estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (2556, 'Compra de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (2557, 'Transferencia de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (2603, 'Ressarcimento de ICMS retido por substituicao tributaria');
insert into vendas.tb_cfop (codigo, descricao) values (2651, 'Compra de combustivel ou lubrificante p/ industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (2652, 'Compra de combustivel ou lubrificante p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (2653, 'Compra de combustivel ou lubrificante por consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (2658, 'Transferencia de combustivel ou lubrificante p/ industrializacao');
insert into vendas.tb_cfop (codigo, descricao) values (2659, 'Transferencia de combustivel ou lubrificante p/ comercializacao ');
insert into vendas.tb_cfop (codigo, descricao) values (2660, 'Devolucao de venda de combustivel ou lubrificante destinados a industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (2661, 'Devolucao de venda de combustivel ou lubrificante destinados a comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (2662, 'Devolucao de venda de combustivel ou lubrificante destinados a consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (2663, 'Entrada de combustivel ou lubrificante p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (2664, 'Retorno de combustivel ou lubrificante remetidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (2901, 'Entrada p/ industrializacao por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (2902, 'Retorno de mercadoria remetida p/ industrializacao por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (2903, 'Entrada de mercadoria remetida p/ industrializacao e nao aplicada no referido processo');
insert into vendas.tb_cfop (codigo, descricao) values (2904, 'Retorno de remessa p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (2905, 'Entrada de mercadoria recebida p/ deposito em deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (2906, 'Retorno de mercadoria remetida p/ deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (2907, 'Retorno simbolico de mercadoria remetida p/ deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (2908, 'Entrada de bem por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (2909, 'Retorno de bem remetido por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (2910, 'Entrada de bonificacao, doacao ou brinde');
insert into vendas.tb_cfop (codigo, descricao) values (2911, 'Entrada de amostra gratis');
insert into vendas.tb_cfop (codigo, descricao) values (2912, 'Entrada de mercadoria ou bem recebido p/ demonstracao');
insert into vendas.tb_cfop (codigo, descricao) values (2913, 'Retorno de mercadoria ou bem remetido p/ demonstracao');
insert into vendas.tb_cfop (codigo, descricao) values (2914, 'Retorno de mercadoria ou bem remetido p/ exposicao ou feira');
insert into vendas.tb_cfop (codigo, descricao) values (2915, 'Entrada de mercadoria ou bem recebido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (2916, 'Retorno de mercadoria ou bem remetido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (2917, 'Entrada de mercadoria recebida em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2918, 'Devolucao de mercadoria remetida em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2919, 'Devolucao simbolica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2920, 'Entrada de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (2921, 'Retorno de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (2922, 'Lancamento efetuado a titulo de simples faturamento decorrente de compra p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (2923, 'Entrada de mercadoria recebida do vendedor remetente, em venda a ordem');
insert into vendas.tb_cfop (codigo, descricao) values (2924, 'Entrada p/ industrializacao por conta e ordem do adquirente da mercadoria, quando esta nao transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (2925, 'Retorno de mercadoria remetida p/ industrializacao por conta e ordem do adquirente da mercadoria, quando esta nao transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (2931, 'Lancamento efetuado pelo tomador do servico de transporte, quando a responsabilidade de retencao do imposto for atribuida ao remetente ou alienante da mercadoria, pelo servico de transporte realizado por transportador autonomo ou por transportador nao-inscrito na UF onde se tenha iniciado o servico  ');
insert into vendas.tb_cfop (codigo, descricao) values (2932, 'Aquisicao de servico de transporte iniciado em UF diversa daquela onde esteja inscrito o prestador ');
insert into vendas.tb_cfop (codigo, descricao) values (2933, 'Aquisicao de servico tributado pelo Imposto Sobre Servicos de Qualquer Natureza');
insert into vendas.tb_cfop (codigo, descricao) values (2934, 'Entrada simbolica de mercadoria recebida p/ deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (2949, 'Outra entrada de mercadoria ou prestacao de servico nao especificado');
insert into vendas.tb_cfop (codigo, descricao) values (3101, 'Compra p/ industrializacao ou producao rural');
insert into vendas.tb_cfop (codigo, descricao) values (3102, 'Compra p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (3126, 'Compra p/ utilizacao na prestacao de servico sujeita ao ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (3127, 'Compra p/ industrializacao sob o regime de drawback ');
insert into vendas.tb_cfop (codigo, descricao) values (3128, 'Compra p/ utilizacao na prestacao de servico sujeita ao ISSQN');
insert into vendas.tb_cfop (codigo, descricao) values (3129, 'Compra para industrializacao sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (3201, 'Devolucao de venda de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (3202, 'Devolucao de venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (3205, 'Anulacao de valor relativo a prestacao de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (3206, 'Anulacao de valor relativo a prestacao de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (3207, 'Anulacao de valor relativo a venda de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (3211, 'Devolucao de venda de producao do estabelecimento sob o regime de drawback ');
insert into vendas.tb_cfop (codigo, descricao) values (3212, 'Devolucao de venda no mercado externo de mercadoria industrializada sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (3251, 'Compra de energia eletrica p/ distribuicao ou comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (3301, 'Aquisicao de servico de comunicacao p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (3351, 'Aquisicao de servico de transporte p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (3352, 'Aquisicao de servico de transporte por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (3353, 'Aquisicao de servico de transporte por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (3354, 'Aquisicao de servico de transporte por estabelecimento de prestador de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (3355, 'Aquisicao de servico de transporte por estabelecimento de geradora ou de distribuidora de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (3356, 'Aquisicao de servico de transporte por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (3503, 'Devolucao de mercadoria exportada que tenha sido recebida com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (3551, 'Compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (3553, 'Devolucao de venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (3556, 'Compra de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (3651, 'Compra de combustivel ou lubrificante p/ industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (3652, 'Compra de combustivel ou lubrificante p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (3653, 'Compra de combustivel ou lubrificante por consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (3930, 'Lancamento efetuado a titulo de entrada de bem sob amparo de regime especial aduaneiro de admissao temporaria');
insert into vendas.tb_cfop (codigo, descricao) values (3949, 'Outra entrada de mercadoria ou prestacao de servico nao especificado');
insert into vendas.tb_cfop (codigo, descricao) values (5101, 'Venda de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5102, 'Venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (5103, 'Venda de producao do estabelecimento efetuada fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5104, 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5105, 'Venda de producao do estabelecimento que nao deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (5106, 'Venda de mercadoria adquirida ou recebida de terceiros, que nao deva por ele transitar ');
insert into vendas.tb_cfop (codigo, descricao) values (5109, 'Venda de producao do estabelecimento destinada a ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (5110, 'Venda de mercadoria, adquirida ou recebida de terceiros, destinada a ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (5111, 'Venda de producao do estabelecimento remetida anteriormente em consignacao industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5112, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignacao industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5113, 'Venda de producao do estabelecimento remetida anteriormente em consignacao mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (5114, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignacao mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (5115, 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignacao mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (5116, 'Venda de producao do estabelecimento originada de encomenda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (5117, 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (5118, 'Venda de producao do estabelecimento entregue ao destinatario por conta e ordem do adquirente originario, em venda a ordem');
insert into vendas.tb_cfop (codigo, descricao) values (5119, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatario por conta e ordem do adquirente originario, em venda a ordem');
insert into vendas.tb_cfop (codigo, descricao) values (5120, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatario pelo vendedor remetente, em venda a ordem');
insert into vendas.tb_cfop (codigo, descricao) values (5122, 'Venda de producao do estabelecimento remetida p/ industrializacao, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (5123, 'Venda de mercadoria adquirida ou recebida de terceiros remetida p/ industrializacao, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (5124, 'Industrializacao efetuada p/ outra empresa');
insert into vendas.tb_cfop (codigo, descricao) values (5125, 'Industrializacao efetuada p/ outra empresa quando a mercadoria recebida p/ utilizacao no processo de industrializacao nao transitar pelo estabelecimento adquirente da mercadoria');
insert into vendas.tb_cfop (codigo, descricao) values (5129, 'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (5151, 'Transferencia de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5152, 'Transferencia de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (5153, 'Transferencia de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (5155, 'Transferencia de producao do estabelecimento, que nao deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (5156, 'Transferencia de mercadoria adquirida ou recebida de terceiros, que nao deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (5201, 'Devolucao de compra p/ industrializacao ou producao rural');
insert into vendas.tb_cfop (codigo, descricao) values (5202, 'Devolucao de compra p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (5205, 'Anulacao de valor relativo a aquisicao de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (5206, 'Anulacao de valor relativo a aquisicao de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (5207, 'Anulacao de valor relativo a compra de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (5208, 'Devolucao de mercadoria recebida em transferencia p/ industrializacao ou producao rural ');
insert into vendas.tb_cfop (codigo, descricao) values (5209, 'Devolucao de mercadoria recebida em transferencia p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (5210, 'Devolucao de compra p/ utilizacao na prestacao de servico');
insert into vendas.tb_cfop (codigo, descricao) values (5251, 'Venda de energia eletrica p/ distribuicao ou comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (5252, 'Venda de energia eletrica p/ estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5253, 'Venda de energia eletrica p/ estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (5254, 'Venda de energia eletrica p/ estabelecimento prestador de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (5255, 'Venda de energia eletrica p/ estabelecimento prestador de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (5256, 'Venda de energia eletrica p/ estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (5257, 'Venda de energia eletrica p/ consumo por demanda contratada');
insert into vendas.tb_cfop (codigo, descricao) values (5258, 'Venda de energia eletrica a nao contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (5301, 'Prestacao de servico de comunicacao p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (5302, 'Prestacao de servico de comunicacao a estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5303, 'Prestacao de servico de comunicacao a estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (5304, 'Prestacao de servico de comunicacao a estabelecimento de prestador de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (5305, 'Prestacao de servico de comunicacao a estabelecimento de geradora ou de distribuidora de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (5306, 'Prestacao de servico de comunicacao a estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (5307, 'Prestacao de servico de comunicacao a nao contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (5351, 'Prestacao de servico de transporte p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (5352, 'Prestacao de servico de transporte a estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5353, 'Prestacao de servico de transporte a estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (5354, 'Prestacao de servico de transporte a estabelecimento de prestador de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (5355, 'Prestacao de servico de transporte a estabelecimento de geradora ou de distribuidora de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (5356, 'Prestacao de servico de transporte a estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (5357, 'Prestacao de servico de transporte a nao contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (5359, 'Prestacao de servico de transporte a contribuinte ou a nao-contribuinte, quando a mercadoria transportada esteja dispensada de emissao de Nota Fiscal  ');
insert into vendas.tb_cfop (codigo, descricao) values (5360, 'Prestacao de servico de transporte a contribuinte-substituto em relacao ao servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (5401, 'Venda de producao do estabelecimento quando o produto esteja sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5402, 'Venda de producao do estabelecimento de produto sujeito a ST, em operacao entre contribuintes substitutos do mesmo produto');
insert into vendas.tb_cfop (codigo, descricao) values (5403, 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita a ST, na condicao de contribuinte-substituto');
insert into vendas.tb_cfop (codigo, descricao) values (5405, 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita a ST, na condicao de contribuinte-substituido');
insert into vendas.tb_cfop (codigo, descricao) values (5408, 'Transferencia de producao do estabelecimento quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5409, 'Transferencia de mercadoria adquirida ou recebida de terceiros em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5410, 'Devolucao de compra p/ industrializacao de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5411, 'Devolucao de compra p/ comercializacao em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5412, 'Devolucao de bem do ativo imobilizado, em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5413, 'Devolucao de mercadoria destinada ao uso ou consumo, em operacao com mercadoria sujeita a ST.');
insert into vendas.tb_cfop (codigo, descricao) values (5414, 'Remessa de producao do estabelecimento p/ venda fora do estabelecimento, quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5415, 'Remessa de mercadoria adquirida ou recebida de terceiros p/ venda fora do estabelecimento, em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5451, 'Remessa de animal e de insumo p/ estabelecimento produtor');
insert into vendas.tb_cfop (codigo, descricao) values (5501, 'Remessa de producao do estabelecimento, com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (5502, 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (5503, 'Devolucao de mercadoria recebida com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (5504, 'Remessa de mercadoria p/ formacao de lote de exportacao, de produto industrializado ou produzido pelo proprio estabelecimento.');
insert into vendas.tb_cfop (codigo, descricao) values (5505, 'Remessa de mercadoria, adquirida ou recebida de terceiros, p/ formacao de lote de exportacao.');
insert into vendas.tb_cfop (codigo, descricao) values (5551, 'Venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (5552, 'Transferencia de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (5553, 'Devolucao de compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (5554, 'Remessa de bem do ativo imobilizado p/ uso fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5555, 'Devolucao de bem do ativo imobilizado de terceiro, recebido p/ uso no estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5556, 'Devolucao de compra de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (5557, 'Transferencia de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (5601, 'Transferencia de credito de ICMS acumulado');
insert into vendas.tb_cfop (codigo, descricao) values (5602, 'Transferencia de saldo credor do ICMS, p/ outro estabelecimento da mesma empresa, destinado a compensacao de saldo devedor do ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (5603, 'Ressarcimento de ICMS retido por substituicao tributaria');
insert into vendas.tb_cfop (codigo, descricao) values (5605, 'Transferencia de saldo devedor do ICMS de outro estabelecimento da mesma empresa  ');
insert into vendas.tb_cfop (codigo, descricao) values (5606, 'Utilizacao de saldo credor do ICMS p/ extincao por compensacao de debitos fiscais');
insert into vendas.tb_cfop (codigo, descricao) values (5651, 'Venda de combustivel ou lubrificante de producao do estabelecimento destinados a industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (5652, 'Venda de combustivel ou lubrificante, de producao do estabelecimento, destinados a comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (5653, 'Venda de combustivel ou lubrificante, de producao do estabelecimento, destinados a consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (5654, 'Venda de combustivel ou lubrificante, adquiridos ou recebidos de terceiros, destinados a industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (5655, 'Venda de combustivel ou lubrificante, adquiridos ou recebidos de terceiros, destinados a comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (5656, 'Venda de combustivel ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (5657, 'Remessa de combustivel ou lubrificante, adquiridos ou recebidos de terceiros, p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5658, 'Transferencia de combustivel ou lubrificante de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5659, 'Transferencia de combustivel ou lubrificante adquiridos ou recebidos de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (5660, 'Devolucao de compra de combustivel ou lubrificante adquiridos p/ industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (5661, 'Devolucao de compra de combustivel ou lubrificante adquiridos p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (5662, 'Devolucao de compra de combustivel ou lubrificante adquiridos por consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (5663, 'Remessa p/ armazenagem de combustivel ou lubrificante');
insert into vendas.tb_cfop (codigo, descricao) values (5664, 'Retorno de combustivel ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (5665, 'Retorno simbolico de combustivel ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (5666, 'Remessa, por conta e ordem de terceiros, de combustivel ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (5667, 'Venda de combustivel ou lubrificante a consumidor ou usuario final estabelecido em outra UF');
insert into vendas.tb_cfop (codigo, descricao) values (5901, 'Remessa p/ industrializacao por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (5902, 'Retorno de mercadoria utilizada na industrializacao por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (5903, 'Retorno de mercadoria recebida p/ industrializacao e nao aplicada no referido processo');
insert into vendas.tb_cfop (codigo, descricao) values (5904, 'Remessa p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5905, 'Remessa p/ deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (5906, 'Retorno de mercadoria depositada em deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (5907, 'Retorno simbolico de mercadoria depositada em deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (5908, 'Remessa de bem por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (5909, 'Retorno de bem recebido por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (5910, 'Remessa em bonificacao, doacao ou brinde');
insert into vendas.tb_cfop (codigo, descricao) values (5911, 'Remessa de amostra gratis');
insert into vendas.tb_cfop (codigo, descricao) values (5912, 'Remessa de mercadoria ou bem p/ demonstracao');
insert into vendas.tb_cfop (codigo, descricao) values (5913, 'Retorno de mercadoria ou bem recebido p/ demonstracao');
insert into vendas.tb_cfop (codigo, descricao) values (5914, 'Remessa de mercadoria ou bem p/ exposicao ou feira');
insert into vendas.tb_cfop (codigo, descricao) values (5915, 'Remessa de mercadoria ou bem p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (5916, 'Retorno de mercadoria ou bem recebido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (5917, 'Remessa de mercadoria em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5918, 'Devolucao de mercadoria recebida em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5919, 'Devolucao simbolica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5920, 'Remessa de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (5921, 'Devolucao de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (5922, 'Lancamento efetuado a titulo de simples faturamento decorrente de venda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (5923, 'Remessa de mercadoria por conta e ordem de terceiros, em venda a ordem ou em operacoes com armazem geral ou deposito fechado.');
insert into vendas.tb_cfop (codigo, descricao) values (5924, 'Remessa p/ industrializacao por conta e ordem do adquirente da mercadoria, quando esta nao transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (5925, 'Retorno de mercadoria recebida p/ industrializacao por conta e ordem do adquirente da mercadoria, quando aquela nao transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (5926, 'Lancamento efetuado a titulo de reclassificacao de mercadoria decorrente de formacao de kit ou de sua desagregacao');
insert into vendas.tb_cfop (codigo, descricao) values (5927, 'Lancamento efetuado a titulo de baixa de estoque decorrente de perda, roubo ou deterioracao');
insert into vendas.tb_cfop (codigo, descricao) values (5928, 'Lancamento efetuado a titulo de baixa de estoque decorrente do encerramento da atividade da empresa');
insert into vendas.tb_cfop (codigo, descricao) values (5929, 'Lancamento efetuado em decorrencia de emissao de documento fiscal relativo a operacao ou prestacao tambem registrada em equipamento Emissor de Cupom Fiscal - ECF');
insert into vendas.tb_cfop (codigo, descricao) values (5931, 'Lancamento efetuado em decorrencia da responsabilidade de retencao do imposto por substituicao tributaria, atribuida ao remetente ou alienante da mercadoria, pelo servico de transporte realizado por transportador autonomo ou por transportador nao inscrito na UF onde iniciado o servico');
insert into vendas.tb_cfop (codigo, descricao) values (5932, 'Prestacao de servico de transporte iniciada em UF diversa daquela onde inscrito o prestador');
insert into vendas.tb_cfop (codigo, descricao) values (5933, 'Prestacao de servico tributado pelo Imposto Sobre Servicos de Qualquer Natureza');
insert into vendas.tb_cfop (codigo, descricao) values (5934, 'Remessa simbolica de mercadoria depositada em armazem geral ou deposito fechado.');
insert into vendas.tb_cfop (codigo, descricao) values (5949, 'Outra saida de mercadoria ou prestacao de servico nao especificado');
insert into vendas.tb_cfop (codigo, descricao) values (6101, 'Venda de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6102, 'Venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (6103, 'Venda de producao do estabelecimento, efetuada fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6104, 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6105, 'Venda de producao do estabelecimento que nao deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (6106, 'Venda de mercadoria adquirida ou recebida de terceiros, que nao deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (6107, 'Venda de producao do estabelecimento, destinada a nao contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6108, 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a nao contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6109, 'Venda de producao do estabelecimento destinada a ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (6110, 'Venda de mercadoria, adquirida ou recebida de terceiros, destinada a ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (6111, 'Venda de producao do estabelecimento remetida anteriormente em consignacao industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6112, 'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignacao industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6113, 'Venda de producao do estabelecimento remetida anteriormente em consignacao mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (6114, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignacao mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (6115, 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignacao mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (6116, 'Venda de producao do estabelecimento originada de encomenda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (6117, 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (6118, 'Venda de producao do estabelecimento entregue ao destinatario por conta e ordem do adquirente originario, em venda a ordem');
insert into vendas.tb_cfop (codigo, descricao) values (6119, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatario por conta e ordem do adquirente originario, em venda a ordem');
insert into vendas.tb_cfop (codigo, descricao) values (6120, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatario pelo vendedor remetente, em venda a ordem');
insert into vendas.tb_cfop (codigo, descricao) values (6122, 'Venda de producao do estabelecimento remetida p/ industrializacao, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (6123, 'Venda de mercadoria adquirida ou recebida de terceiros remetida p/ industrializacao, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (6124, 'Industrializacao efetuada p/ outra empresa');
insert into vendas.tb_cfop (codigo, descricao) values (6125, 'Industrializacao efetuada p/ outra empresa quando a mercadoria recebida p/ utilizacao no processo de industrializacao nao transitar pelo estabelecimento adquirente da mercadoria');
insert into vendas.tb_cfop (codigo, descricao) values (6129, 'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (6151, 'Transferencia de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6152, 'Transferencia de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (6153, 'Transferencia de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (6155, 'Transferencia de producao do estabelecimento, que nao deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (6156, 'Transferencia de mercadoria adquirida ou recebida de terceiros, que nao deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (6201, 'Devolucao de compra p/ industrializacao ou producao rural');
insert into vendas.tb_cfop (codigo, descricao) values (6202, 'Devolucao de compra p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (6205, 'Anulacao de valor relativo a aquisicao de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (6206, 'Anulacao de valor relativo a aquisicao de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (6207, 'Anulacao de valor relativo a compra de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (6208, 'Devolucao de mercadoria recebida em transferencia p/ industrializacao ou producao rural ');
insert into vendas.tb_cfop (codigo, descricao) values (6209, 'Devolucao de mercadoria recebida em transferencia p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (6210, 'Devolucao de compra p/ utilizacao na prestacao de servico');
insert into vendas.tb_cfop (codigo, descricao) values (6251, 'Venda de energia eletrica p/ distribuicao ou comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (6252, 'Venda de energia eletrica p/ estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6253, 'Venda de energia eletrica p/ estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (6254, 'Venda de energia eletrica p/ estabelecimento prestador de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (6255, 'Venda de energia eletrica p/ estabelecimento prestador de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (6256, 'Venda de energia eletrica p/ estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (6257, 'Venda de energia eletrica p/ consumo por demanda contratada');
insert into vendas.tb_cfop (codigo, descricao) values (6258, 'Venda de energia eletrica a nao contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6301, 'Prestacao de servico de comunicacao p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (6302, 'Prestacao de servico de comunicacao a estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6303, 'Prestacao de servico de comunicacao a estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (6304, 'Prestacao de servico de comunicacao a estabelecimento de prestador de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (6305, 'Prestacao de servico de comunicacao a estabelecimento de geradora ou de distribuidora de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (6306, 'Prestacao de servico de comunicacao a estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (6307, 'Prestacao de servico de comunicacao a nao contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6351, 'Prestacao de servico de transporte p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (6352, 'Prestacao de servico de transporte a estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6353, 'Prestacao de servico de transporte a estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (6354, 'Prestacao de servico de transporte a estabelecimento de prestador de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (6355, 'Prestacao de servico de transporte a estabelecimento de geradora ou de distribuidora de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (6356, 'Prestacao de servico de transporte a estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (6357, 'Prestacao de servico de transporte a nao contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6359, 'Prestacao de servico de transporte a contribuinte ou a nao-contribuinte, quando a mercadoria transportada esteja dispensada de emissao de Nota Fiscal  ');
insert into vendas.tb_cfop (codigo, descricao) values (6360, 'Prestacao de servico de transporte a contribuinte substituto em relacao ao servico de transporte  ');
insert into vendas.tb_cfop (codigo, descricao) values (6401, 'Venda de producao do estabelecimento quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6402, 'Venda de producao do estabelecimento de produto sujeito a ST, em operacao entre contribuintes substitutos do mesmo produto');
insert into vendas.tb_cfop (codigo, descricao) values (6403, 'Venda de mercadoria adquirida ou recebida de terceiros em operacao com mercadoria sujeita a ST, na condicao de contribuinte substituto');
insert into vendas.tb_cfop (codigo, descricao) values (6404, 'Venda de mercadoria sujeita a ST, cujo imposto ja tenha sido retido anteriormente');
insert into vendas.tb_cfop (codigo, descricao) values (6408, 'Transferencia de producao do estabelecimento quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6409, 'Transferencia de mercadoria adquirida ou recebida de terceiros, sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6410, 'Devolucao de compra p/ industrializacao ou ptroducao rural quando a mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6411, 'Devolucao de compra p/ comercializacao em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6412, 'Devolucao de bem do ativo imobilizado, em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6413, 'Devolucao de mercadoria destinada ao uso ou consumo, em operacao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6414, 'Remessa de producao do estabelecimento p/ venda fora do estabelecimento, quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6415, 'Remessa de mercadoria adquirida ou recebida de terceiros p/ venda fora do estabelecimento, quando a referida racao com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6501, 'Remessa de producao do estabelecimento, com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (6502, 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (6503, 'Devolucao de mercadoria recebida com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (6504, 'Remessa de mercadoria p/ formacao de lote de exportacao, de produto industrializado ou produzido pelo proprio estabelecimento.');
insert into vendas.tb_cfop (codigo, descricao) values (6505, 'Remessa de mercadoria, adquirida ou recebida de terceiros, p/ formacao de lote de exportacao.');
insert into vendas.tb_cfop (codigo, descricao) values (6551, 'Venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (6552, 'Transferencia de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (6553, 'Devolucao de compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (6554, 'Remessa de bem do ativo imobilizado p/ uso fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6555, 'Devolucao de bem do ativo imobilizado de terceiro, recebido p/ uso no estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6556, 'Devolucao de compra de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (6557, 'Transferencia de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (6603, 'Ressarcimento de ICMS retido por substituicao tributaria');
insert into vendas.tb_cfop (codigo, descricao) values (6651, 'Venda de combustivel ou lubrificante, de producao do estabelecimento, destinados a industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (6652, 'Venda de combustivel ou lubrificante, de producao do estabelecimento, destinados a comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (6653, 'Venda de combustivel ou lubrificante, de producao do estabelecimento, destinados a consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (6654, 'Venda de combustivel ou lubrificante, adquiridos ou recebidos de terceiros, destinados a industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (6655, 'Venda de combustivel ou lubrificante, adquiridos ou recebidos de terceiros, destinados a comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (6656, 'Venda de combustivel ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (6657, 'Remessa de combustivel ou lubrificante, adquiridos ou recebidos de terceiros, p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6658, 'Transferencia de combustivel ou lubrificante de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6659, 'Transferencia de combustivel ou lubrificante adquiridos ou recebidos de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (6660, 'Devolucao de compra de combustivel ou lubrificante adquiridos p/ industrializacao subsequente');
insert into vendas.tb_cfop (codigo, descricao) values (6661, 'Devolucao de compra de combustivel ou lubrificante adquiridos p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (6662, 'Devolucao de compra de combustivel ou lubrificante adquiridos por consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (6663, 'Remessa p/ armazenagem de combustivel ou lubrificante');
insert into vendas.tb_cfop (codigo, descricao) values (6664, 'Retorno de combustivel ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (6665, 'Retorno simbolico de combustivel ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (6666, 'Remessa, por conta e ordem de terceiros, de combustivel ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (6667, 'Venda de combustivel ou lubrificante a consumidor ou usuario final estabelecido em outra UF diferente da que ocorrer o consumo');
insert into vendas.tb_cfop (codigo, descricao) values (6901, 'Remessa p/ industrializacao por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (6902, 'Retorno de mercadoria utilizada na industrializacao por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (6903, 'Retorno de mercadoria recebida p/ industrializacao e nao aplicada no referido processo');
insert into vendas.tb_cfop (codigo, descricao) values (6904, 'Remessa p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6905, 'Remessa p/ deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (6906, 'Retorno de mercadoria depositada em deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (6907, 'Retorno simbolico de mercadoria depositada em deposito fechado ou armazem geral');
insert into vendas.tb_cfop (codigo, descricao) values (6908, 'Remessa de bem por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (6909, 'Retorno de bem recebido por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (6910, 'Remessa em bonificacao, doacao ou brinde');
insert into vendas.tb_cfop (codigo, descricao) values (6911, 'Remessa de amostra gratis');
insert into vendas.tb_cfop (codigo, descricao) values (6912, 'Remessa de mercadoria ou bem p/ demonstracao');
insert into vendas.tb_cfop (codigo, descricao) values (6913, 'Retorno de mercadoria ou bem recebido p/ demonstracao');
insert into vendas.tb_cfop (codigo, descricao) values (6914, 'Remessa de mercadoria ou bem p/ exposicao ou feira');
insert into vendas.tb_cfop (codigo, descricao) values (6915, 'Remessa de mercadoria ou bem p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (6916, 'Retorno de mercadoria ou bem recebido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (6917, 'Remessa de mercadoria em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6918, 'Devolucao de mercadoria recebida em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6919, 'Devolucao simbolica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignacao mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6920, 'Remessa de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (6921, 'Devolucao de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (6922, 'Lancamento efetuado a titulo de simples faturamento decorrente de venda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (6923, 'Remessa de mercadoria por conta e ordem de terceiros, em venda a ordem ou em operacoes com armazem geral ou deposito fechado');
insert into vendas.tb_cfop (codigo, descricao) values (6924, 'Remessa p/ industrializacao por conta e ordem do adquirente da mercadoria, quando esta nao transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (6925, 'Retorno de mercadoria recebida p/ industrializacao por conta e ordem do adquirente da mercadoria, quando aquela nao transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (6929, 'Lancamento efetuado em decorrencia de emissao de documento fiscal relativo a operacao ou prestacao tambem registrada em equipamento Emissor de Cupom Fiscal - ECF');
insert into vendas.tb_cfop (codigo, descricao) values (6931, 'Lancamento efetuado em decorrencia da responsabilidade de retencao do imposto por substituicao tributaria, atribuida ao remetente ou alienante da mercadoria, pelo servico de transporte realizado por transportador autonomo ou por transportador nao inscrito na UF onde iniciado o servico');
insert into vendas.tb_cfop (codigo, descricao) values (6932, 'Prestacao de servico de transporte iniciada em UF diversa daquela onde inscrito o prestador');
insert into vendas.tb_cfop (codigo, descricao) values (6933, 'Prestacao de servico tributado pelo Imposto Sobre Servicos de Qualquer Natureza ');
insert into vendas.tb_cfop (codigo, descricao) values (6934, 'Remessa simbolica de mercadoria depositada em armazem geral ou deposito fechado');
insert into vendas.tb_cfop (codigo, descricao) values (6949, 'Outra saida de mercadoria ou prestacao de servico nao especificado');
insert into vendas.tb_cfop (codigo, descricao) values (7101, 'Venda de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (7102, 'Venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (7105, 'Venda de producao do estabelecimento, que nao deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (7106, 'Venda de mercadoria adquirida ou recebida de terceiros, que nao deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (7127, 'Venda de producao do estabelecimento sob o regime de drawback ');
insert into vendas.tb_cfop (codigo, descricao) values (7129, 'Venda de producao do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (7201, 'Devolucao de compra p/ industrializacao ou producao rural');
insert into vendas.tb_cfop (codigo, descricao) values (7202, 'Devolucao de compra p/ comercializacao');
insert into vendas.tb_cfop (codigo, descricao) values (7205, 'Anulacao de valor relativo a aquisicao de servico de comunicacao');
insert into vendas.tb_cfop (codigo, descricao) values (7206, 'Anulacao de valor relativo a aquisicao de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (7207, 'Anulacao de valor relativo a compra de energia eletrica');
insert into vendas.tb_cfop (codigo, descricao) values (7210, 'Devolucao de compra p/ utilizacao na prestacao de servico');
insert into vendas.tb_cfop (codigo, descricao) values (7211, 'Devolucao de compras p/ industrializacao sob o regime de drawback ');
insert into vendas.tb_cfop (codigo, descricao) values (7212, 'Devolucao de compras para industrializacao sob o regime de Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (7251, 'Venda de energia eletrica p/ o exterior');
insert into vendas.tb_cfop (codigo, descricao) values (7301, 'Prestacao de servico de comunicacao p/ execucao de servico da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (7358, 'Prestacao de servico de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (7501, 'Exportacao de mercadorias recebidas com fim especifico de exportacao');
insert into vendas.tb_cfop (codigo, descricao) values (7551, 'Venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (7553, 'Devolucao de compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (7556, 'Devolucao de compra de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (7651, 'Venda de combustivel ou lubrificante de producao do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (7654, 'Venda de combustivel ou lubrificante adquiridos ou recebidos de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (7667, 'Venda de combustivel ou lubrificante a consumidor ou usuario final');
insert into vendas.tb_cfop (codigo, descricao) values (7930, 'Lancamento efetuado a titulo de devolucao de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissao temporaria');
insert into vendas.tb_cfop (codigo, descricao) values (7949, 'Outra saida de mercadoria ou prestacao de servico nao especificado');
